version: '3.8'

services:
  hr-import-service:
    image: hr-import-service:1.0.0
    container_name: hr-import-service
    restart: always
    ports:
      - "13801:13801"
    volumes:
      - /opt/ai3/java:/opt/ai3/java:ro
      - /opt/ai3/input:/opt/ai3/input
      - /opt/ai3/archive:/opt/ai3/archive
      - /opt/ai3/jar/docker/hrimport/logs:/app/logs
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    tty: true
    command: >
      /opt/ai3/java/jdk-17.0.2/bin/java -Dfile.encoding=UTF-8 -jar /app/hr-import-service-1.0.0.jar --logging.charset.file=UTF-8

