spring:
  datasource:
    url: jdbc:postgresql://192.168.112.146:5432/ai3ecp
    username: ai3
    password: ai3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # 啟用自動引號，讓 Hibernate 使用實體上標註的表名/欄位名稱大小寫
        globally_quoted_identifiers: true
        # 明確設定命名策略
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        # 禁用物理命名策略
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 13801
  tomcat:
    use-apr: false
app:
  sftp:
    host: ${SFTP_HOST:10.2.3.4}
    port: ${SFTP_PORT:22}
    username: ${SFTP_USERNAME:ftpuser}
    password: ${SFTP_PASSWORD:ai3[1qaz@WSX]}
    remote-path: ${SFTP_PATH:/hrfile/}
    local-dir: ${LOCAL_DIR:/tmp/hr-import}
    # Optional: only download the specified filename from SFTP (defaults to HrImport.csv)
    filename: HrImport.csv
  processing:
    enabled-states: A
    disabled-states: C,B,D,E
  default-password: "loclmjbekjjpejbkllnpebakjcgaifekgniemamkggajjbmmgdnhfgmfnchakhgnaflbahapbfokenfd"
  ts:
    # starting FTreeSerial for level-2 generation. Example: 001.001 -> level2 starts from 001.001
    start-ftreeserial: "001.001"
    # Top-level/root TsDepartment FId used as parent for tree level 2 departments
    root-fid: "00000000-0000-0000-1001-000000000001"
    # Dept-level fixed user id (FUserId) to set on TsDepartment rows when syncing
    dept-user-id: "00000000-0000-0000-1002-000000000001"
  # default FIdentityTypeId to insert into TsAccountIdentity; structured as a map with id and rol_user_id
  identity-type-id:
    id: "564cf69e-76d6-4baf-b584-6e04c2911dae"
    rol_user_id: "19bf8429-91e0-090e-57f8-2a1bf1c7db25"
  # Configure the tree level threshold under which employee department will be updated (default 4)
  tree-label-update-dep: 7

logging:
  level:
    ROOT: DEBUG
    com.citic.hrimport: DEBUG
  file:
    name: logs/hr-import.log
  charset:
    file: UTF-8
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
scheduler:
  hrimport:
    enabled: true         # true: 每分鐘會跑 ; false: 完全停用
    cron: "0 * * * * *"   # 每分鐘一次
    localPath: "/home/ai3/HrImportFile/input"
    localArchivePath: "/home/ai3/HrImportFile/archive"
    # 本機要處理的 CSV 檔名（只處理此檔案）
    filename: HrImport.csv
